### ISSUE TITLE
where is the Base_OVAD_C4_1x_average_att.yaml file?

### ISSUE THREAD

**Issue by Code-kunkun** [OVAD-Benchmark/ovad-benchmark-code#3]
<img width="591" alt="image" src="https://github.com/OVAD-Benchmark/ovad-benchmark-code/assets/58265850/47dc7f2e-48f4-40e4-9cdc-8793bd37f833">

I want to know where is the `configs/Base_OVAD_C4_1x_average_att.yaml` file?

**Comment by mabravo641** [comment]
Dear @Code-kunkun, thanks for pointing out a typo in the command. The configuration file name is [Base_OVAD_C4_1x.yaml](https://github.com/OVAD-Benchmark/ovad-benchmark-code/blob/main/configs/Base_OVAD_C4_1x.yaml)
Please find it in the configs directory.

**Comment by Code-kunkun** [comment]
Thanks!!!
